function [trials, op] = generate_trial_table(op, paths)

%% create table describing stimuli for each trial of dbs-learn experiment
%
%   this script contains the number of of repetitions for each stimulus condition in each phase
%
% NB: for training phases, where there are only 2 unique stim, it can take a few seconds to find a stim order when op.max_repeated_trials == 3
% ..... op.max_repeated_trials = 2 will likely lag infinitely
% ..... further optimization could probably speed up this randomization for low values of op.max_repeated_trials
% 
% By Andrew Meier @ Guenther Lab, 2026


%% initial setup and parameters

%%% specify the number of repetitions for each stim group within each task
% no entries for famil or assses because we just present the lists once in order
stim_reps_by_task = {...

    % subsyl tasks - CCVC
    'subsyl','famil','famil','ccvc', 1;...

    'subsyl','pretest','trainA','ccvc', 2;...
    'subsyl','pretest','trainB','ccvc', 2;...
    'subsyl','pretest','novel1_nat','ccvc', 2;...
    'subsyl','pretest','novel1_nn','ccvc', 2;...
    'subsyl','pretest','novel2_nat','ccvc', 2;...
    'subsyl','pretest','novel2_nn','ccvc', 2;...
    
    'subsyl', 'trainA', 'trainA','ccvc', 75;...

    'subsyl', 'trainB', 'trainB','ccvc', 75;...

    'subsyl', 'test1',   'trainA','ccvc', 20;...
    'subsyl', 'test1',   'trainB','ccvc', 20;...
    'subsyl', 'test1',  'novel1_nat','ccvc', 10;...
    'subsyl', 'test1',  'novel1_nn','ccvc', 10;...

    'subsyl', 'test2',   'trainA','ccvc', 20;...
    'subsyl', 'test2',   'trainB','ccvc', 20;...
    'subsyl', 'test2',  'novel2_nat','ccvc', 10;...
    'subsyl', 'test2',  'novel2_nn','ccvc', 10;...

    % subsyl tasks - CCVCC
    'subsyl','famil','famil','ccvcc', 1;...

    'subsyl','pretest','trainA','ccvcc', 2;...
    'subsyl','pretest','trainB','ccvcc', 2;...
    'subsyl','pretest','novel1_nat','ccvcc', 2;...
    'subsyl','pretest','novel1_nn','ccvcc', 2;...
    'subsyl','pretest','novel2_nat','ccvcc', 2;...
    'subsyl','pretest','novel2_nn','ccvcc', 2;...
    
    'subsyl', 'trainA', 'trainA','ccvcc', 60;...

    'subsyl', 'trainB', 'trainB','ccvcc', 60;...

    'subsyl', 'test1',   'trainA','ccvcc', 15;...
    'subsyl', 'test1',   'trainB','ccvcc', 15;...
    'subsyl', 'test1',  'novel1_nat','ccvcc', 8;...
    'subsyl', 'test1',  'novel1_nn','ccvcc', 8;...

    'subsyl', 'test2',   'trainA','ccvcc', 15;...
    'subsyl', 'test2',   'trainB','ccvcc', 15;...
    'subsyl', 'test2',  'novel2_nat','ccvcc', 8;...
    'subsyl', 'test2',  'novel2_nn','ccvcc', 8;...

    % multisyl tasks
    'multisyl', 'fds', 'fds','', 1;....

    'multisyl','famil','famil','', 1;...

    'multisyl','assess','assess','', 1;...
    
    'multisyl','pretest','trainA','', 2;...
    'multisyl','pretest','trainB','', 2;...
    'multisyl','pretest','novel1','', 2;...
    'multisyl','pretest','novel2','', 2;...

    'multisyl', 'trainA', 'trainA','', 65;...

    'multisyl', 'trainB', 'trainB','', 65;...

    'multisyl', 'test1', 'trainA','', 25;... 
    'multisyl', 'test1', 'trainB','', 25;... 
    'multisyl', 'test1', 'novel1','', 10;... 

    'multisyl', 'test2', 'trainA','', 25;... 
    'multisyl', 'test2', 'trainB','', 25;... 
    'multisyl', 'test2', 'novel2','', 10;... 

    };


stim_reps_by_task = cell2table(stim_reps_by_task, 'VariableNames',{'ses','task','stim_group','syl_struct','reps_per_unq_stim'});

op.stim_master_file = [paths.code_dbs_learn, filesep, 'stim_master_', op.ses, '.tsv']; 
stim_master = readtable(op.stim_master_file,'FileType','text'); 

stim_reps_tab = stim_reps_by_task(stim_reps_by_task.ses == string(op.ses)  & ...
                                  stim_reps_by_task.task == string(op.task), :); 

% for subsyl, look only for the stim w/ the syllable structure we've specified in op
if op.ses == "subsyl"
     stim_master = stim_master(stim_master.syl_struct == string(op.syl_struct), :);
     stim_reps_tab = stim_reps_tab(stim_reps_tab.syl_struct == string(op.syl_struct), :); 
end

if op.task == "famil" || op.task == "assess" || op.task=="fds" % if familiarization or assessment phase, just take the exact listed stim in order
    trials = stim_master(stim_master.stim_group == string(op.task), : );
else % for training/testing, stim list needs to be sorted / multiplied / shuffled 

    switch op.task
        case 'pretest'
            field_default('op','max_repeated_trials', 1);
        otherwise 
            field_default('op','max_repeated_trials', 3); 
    end
    
    trials = table; 

    % for multisyl, keep only stim with this subject's selected syllable count (does not apply to famil/assess)
    if op.ses == "multisyl"
        stim_master = stim_master(stim_master.n_syllables == op.subj_n_syls, :); 
    end

    n_stim_groups = height(stim_reps_tab);
    for igroup = 1:n_stim_groups
        thisgroup = stim_reps_tab.stim_group{igroup};
        stim_in_group = stim_master(stim_master.stim_group==string(thisgroup), :); 

        % make copies of stim in this group and add it to the trials table; 
        trials = [trials; repmat(stim_in_group, stim_reps_tab.reps_per_unq_stim(igroup), 1)];
    end
    op.ntrials = height(trials); 

    % shuffle stim and make sure that we don't exceed the max allowed number of sequential repetitions of a stim
    max_reps_in_a_row = inf; 
    while max_reps_in_a_row > op.max_repeated_trials
        trials = trials(randperm(op.ntrials), :); % shuffle trials
        [~,~,stiminds] = unique(trials.name); 

        max_reps_in_a_row = 1; 
        streak = 1; 
        for itrial = 2:op.ntrials
            if stiminds(itrial)==stiminds(itrial-1)
                streak = streak+1;
                max_reps_in_a_row = max(max_reps_in_a_row, streak); 
            else
                streak = 1; 
            end
        end
    end


end

op.ntrials = height(trials); 
nancol = nan(op.ntrials,1);
trialnum = [1:op.ntrials]';
trials = [trials, table(trialnum, nancol,nancol,nancol,nancol,nancol,nancol,nancol,nancol,'VariableNames',...
    {                    'trialnum', 't_stim_vis_on','t_stim_vis_off','t_stim_aud_on','t_stim_aud_off','t_go_vis_on','t_go_aud_on','t_go_aud_off','go_delay'})]; 
trials = movevars(trials,{'trialnum'},'Before',1); 